import { IconType } from "react-icons";

import {
  HiOutlineRocketLaunch,
  HiOutlineBolt,
  HiOutlineShieldCheck,
  HiOutlineBookOpen,
  HiOutlineChartBar,
  HiOutlineClock,
  HiOutlineKey,
  HiOutlineBell,
  HiOutlineCodeBracket,
  HiOutlineArrowDownTray,
  HiOutlineSquares2X2,
  HiOutlineQueueList,
  HiOutlineCog6Tooth,
  HiOutlineUsers,
  HiOutlineFolder,
  HiOutlineUserPlus,
  HiOutlineArrowPath,
  HiOutlineChevronDown,
  HiOutlineXMark,
  HiOutlineChatBubbleLeftRight,
  HiOutlinePencilSquare,
  HiOutlineTrash,
  HiOutlineDocumentArrowDown,
  HiOutlineExclamationTriangle,
  HiOutlinePhone,
  HiOutlinePlus,
} from "react-icons/hi2";

export const iconLibrary: Record<string, IconType> = {
  rocket: HiOutlineRocketLaunch,
  lightning: HiOutlineBolt,
  zap: HiOutlineBolt,
  shield: HiOutlineShieldCheck,
  book: HiOutlineBookOpen,
  gauge: HiOutlineChartBar,
  clock: HiOutlineClock,
  key: HiOutlineKey,
  bell: HiOutlineBell,
  code: HiOutlineCodeBracket,
  download: HiOutlineArrowDownTray,
  grid: HiOutlineSquares2X2,
  list: HiOutlineQueueList,
  settings: HiOutlineCog6Tooth,
  user: HiOutlineUsers,
  folder: HiOutlineFolder,
  userPlus: HiOutlineUserPlus,
  refresh: HiOutlineArrowPath,
  chevronDown: HiOutlineChevronDown,
  x: HiOutlineXMark,
  message: HiOutlineChatBubbleLeftRight,
  edit: HiOutlinePencilSquare,
  trash: HiOutlineTrash,
  save: HiOutlineDocumentArrowDown,
  alert: HiOutlineExclamationTriangle,
  phone: HiOutlinePhone,
  plus: HiOutlinePlus,
};

export type IconLibrary = typeof iconLibrary;
export type IconName = keyof IconLibrary;
